/**
 * Regression test for issue #2157: `.claude/skills/create-skill/SKILL.md`
 * mandated `mktemp "/tmp/tmp.XXXXXXXXXX.ext"` as its "portable"
 * temp-file template. BSD `mktemp` (macOS) only randomizes a TRAILING run
 * of `X`s — a suffix directly after it returns the template literally
 * instead of creating a unique path, so every skill generated by
 * `/create-skill` following that pattern got a fixed, non-unique temp path
 * on macOS: concurrent sessions collided on the same literal file, and
 * re-runs failed outright with "mkstemp failed ... File exists".
 *
 * The fix rewrites every mandated example to use a trailing-X `mktemp -d`
 * template (creating a temp directory) with the extensioned file placed
 * inside it, and adds a `lint-skill.sh` check (this test's subject) so a
 * future skill reintroducing the broken pattern is caught automatically.
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..', '..');
const LINT_SCRIPT = path.join(
  REPO_ROOT,
  '.claude',
  'skills',
  'create-skill',
  'scripts',
  'lint-skill.sh',
);

const FRONTMATTER = `---
name: lint-test-skill
description: test
argument-hint: none
allowed-tools: Bash
---

## Phase 0

pre-flight

## Rules

rules here

## Examples

example here
`;

function runLint(bashBlock: string): { stdout: string; status: number | null } {
  const content = `${FRONTMATTER}\n\`\`\`bash\n${bashBlock}\n\`\`\`\n\n**Exit condition:** done\n`;
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'lint-skill-mktemp-'));
  const skillPath = path.join(dir, 'SKILL.md');
  fs.writeFileSync(skillPath, content);
  try {
    const result = execFileSync('bash', [LINT_SCRIPT, skillPath], { encoding: 'utf8' });
    return { stdout: result, status: 0 };
  } catch (err) {
    const e = err as { stdout?: string; status?: number | null };
    return { stdout: e.stdout ?? '', status: e.status ?? 1 };
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

describe('lint-skill.sh flags mktemp templates with a non-trailing X run (#2157)', () => {
  it('flags a suffix directly after the X run (the exact bug reported)', () => {
    const { stdout } = runLint('TMPFILE=$(mktemp "/tmp/tmp.XXXXXXXXXX.js")');
    expect(stdout).toContain("mktemp template's X run is not trailing");
  });

  it('flags a non-extension suffix too (any character directly after the X run)', () => {
    const { stdout } = runLint('BLOCKS_FILE=$(mktemp "/tmp/tmp.XXXXXXXXXX.blocks")');
    expect(stdout).toContain("mktemp template's X run is not trailing");
  });

  it('does not flag a trailing-X-only template', () => {
    const { stdout } = runLint('TMPFILE=$(mktemp "/tmp/tmp.XXXXXXXXXX")');
    expect(stdout).not.toContain("mktemp template's X run is not trailing");
  });

  it('does not flag mktemp -d with a trailing-X template (the recommended fix)', () => {
    const { stdout } = runLint(
      [
        'TMP_DIR=$(mktemp -d "/tmp/tmp.XXXXXXXXXX")',
        'trap \'rm -rf "$TMP_DIR"\' EXIT',
        'TMP_FILE="$TMP_DIR/probe.js"',
      ].join('\n'),
    );
    expect(stdout).not.toContain("mktemp template's X run is not trailing");
  });

  it('does not flag a bare mktemp -d with no template at all', () => {
    const { stdout } = runLint('WORK_DIR=$(mktemp -d)');
    expect(stdout).not.toContain("mktemp template's X run is not trailing");
  });
});

describe('.claude/skills/create-skill/SKILL.md itself has no non-trailing-X mktemp templates', () => {
  it('passes lint-skill.sh with no mktemp-related warnings', () => {
    const realSkillPath = path.join(REPO_ROOT, '.claude', 'skills', 'create-skill', 'SKILL.md');
    let stdout: string;
    try {
      stdout = execFileSync('bash', [LINT_SCRIPT, realSkillPath], { encoding: 'utf8' });
    } catch (err) {
      stdout = (err as { stdout?: string }).stdout ?? '';
    }
    expect(stdout).not.toContain("mktemp template's X run is not trailing");
  });
});
